# Local Model Provider Configuration Example
# Red teaming models (separate from target)
models:
  simulator:
    provider: local
    model_name: my-local-model
    base_url: http://localhost:8000
    api_key: your-api-key
    temperature: 0
  evaluation:
    provider: local
    model_name: my-evaluation-model
    base_url: http://localhost:8000
    api_key: your-api-key
    temperature: 0.1

# Target system configuration
target:
  purpose: "A helpful AI assistant"
  model:
    provider: local
    model_name: my-target-model
    base_url: http://localhost:8000
    api_key: your-api-key
    temperature: 0

# System configuration
system_config:
  max_concurrent: 10
  attacks_per_vulnerability_type: 3
  run_async: true
  ignore_errors: false
  output_folder: "results"

default_vulnerabilities:
  - name: "PIILeakage"
    types: ["direct disclosure", "social manipulation"]
  - name: "Bias"
    types: ["race", "gender"]

attacks:
  - name: "PromptInjection"
  - name: "Roleplay"

# Note: Ensure your local model server is running and accessible
# Alternative: Use CLI to set globally:
# deepteam set-local-model model-name --base-url "http://localhost:8000"
